AgileEstate/AgileEstate/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from .views import main_page

urlpatterns = [
    url(r'^$', main_page, name='main_page'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^profile/', include("users.urls", namespace="users")),
    url(r'^estate/', include("estate.urls", namespace="estate")),
    url(r'^bidding/', include("auction.urls", namespace="auction")),
]

AgileEstate/users/urls.py
from django.conf.urls import url
from . import views

app_name = "users"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'profile/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile),
]

AgileEstate/users/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    location = models.CharField(max_length=140)
    gender = models.CharField(max_length=140)
    firstname = models.CharField(max_length=140)
    lastname = models.CharField(max_length=140)
    profile_picture = models.CharField(max_length=140)

    def __unicode__( self ):
        return self.firstname + " " + self.lastname

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

AgileEstate/users/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models
from .models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['gender','firstname','lastname']

AgileEstate/users/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render
from estate.models import EstateModel
from .forms import UserForm, UserProfileForm
from .models import UserProfile



# Create your views here.

def index(request):
    return render(request, 'main.html')
    
def register(request):
    userForm = UserForm(request.POST or None)
    profileForm = UserProfileForm(request.POST or None)
    if userForm.is_valid():
        user = userForm.save(commit=False)
        username = userForm.cleaned_data['username']
        password = userForm.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if profileForm.is_valid():

            gender = profileForm.cleaned_data['gender']
            firstname = profileForm.cleaned_data['firstname']
            lastname = profileForm.cleaned_data['lastname']
            profile = UserProfile(user=user,gender=gender,firstname=firstname,lastname=lastname)
            profile.save()

        else:
            profile = None

        estates = EstateModel.objects.filter(owner_key=profile)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'profile/user_profile.html', {"user":user,"profile":profile,"estates":estates})
    context = {
        "userForm": userForm,
        "profileForm": profileForm
    }
    return render(request, 'profile/register.html', context)

def logout_user(request):
    logout(request)
    return render(request, 'main.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print('Tried to log on to:' + username + "; " + password)
        user = authenticate(username=username, password=password)
        profile = UserProfile.objects.get(user=user)
        estates = EstateModel.objects.filter(owner_key=profile)
        print(estates)
        print("okay")
        if user is not None:
            print("user found")
            if user.is_active:
                login(request, user)
                print("logged on")
                return render(request, 'profile/user_profile.html', {"user":user,"profile":profile,"estates":estates})
            else:
                return render(request, 'profile/login.html', {'error_message': 'Your account has been disabled'})
        else:
            print("user not found")
            return render(request, 'profile/login.html', {'error_message': 'Invalid login'})
    return render(request, 'profile/login.html')

def get_user_profile(request, username):
    user = User.objects.get(username=username)
    profile = UserProfile.objects.get(user=user)
    estates = EstateModel.objects.filter(owner_key=profile)
    print(estates)
    return render(request, 'profile/user_profile.html', {"user":user,"profile":profile,"estates":estates})

from django.shortcuts import render

AgileEstate/users/templates/profile/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'users:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'users:login_user' %}">Log in</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                 <li>
                     <a href="{% url 'users:logout_user' %}">
                         <span aria-hidden="true"></span>&nbsp; Main page
                     </a>
                 </li>
             </ul>
        </div>



    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

AgileEstate/users/templates/profile/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'users:index' %}">Main page</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav navbar-right">
               <li>
                   <a href="{% url 'users:logout_user' %}">
                       <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log out
                   </a>
               </li>
           </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

AgileEstate/users/templates/profile/index.html
{% extends 'profile/base_visitor.html' %}

{% block content %}

 <H1> Hello </H1>

{% endblock %}

AgileEstate/users/templates/profile/login.html
{% extends 'profile/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log in</h3>
                    <form class="form-horizontal" role="form" action="{% url 'users:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Log in</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account yet? <a href="{% url 'users:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

AgileEstate/users/templates/profile/register.html
{% extends 'profile/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register new account</h3>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in userForm %}
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="user_name">{{ field.label_tag }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                        {% endfor %}
                        {% for field in profileForm %}
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="user_name">{{ field.label_tag }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'users:login_user' %}">Click here!</a> To login.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

AgileEstate/users/templates/profile/user_profile.html
{% extends 'profile/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<table class="table">
  <tr>
    <th>Icon</th>
    <th>Username</th>
    <th>E-mail</th>
    <th>First Name</th>
    <th>Second Name</th>
    <th>Gender</th>
  <tr>
    <td style="height: 80px; width: 30px;"><img style="max-width: 100%;max-height: 100%;" src= {{ profile.profile_picture }}></td>
   <td>{{ user.username }}</td>
   <td>{{ user.email }}</td>
   <td>{{ profile.firstname }}</td>
   <td>{{ profile.lastname }}</td>
   <td>{{ profile.gender }}</td>
 </tr>

</table>

<h1>My Estates</h1>

<table class='table'>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Surface</th>
    <th>Window view</th>
  <tr>
  {% for estate in estates%}
  <tr>
    <td> {{estate.get_latitude}} </td>
    <td> {{estate.get_longitude}} </td>
    <td> {{estate.surface}} </td>
    <td> {{estate.get_window_view_name}} </td>
  </tr>
  {% endfor %}
</table>

{% endblock %}