AgileEstate/AgileEstate/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from .views import main_page

urlpatterns = [
    url(r'^$', main_page, name='main_page'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^profile/', include("users.urls", namespace="users")),
    url(r'^estate/', include("estate.urls", namespace="estate")),
    url(r'^bidding/', include("auction.urls", namespace="auction")),
]

AgileEstate/auction/urls.py
from django.conf.urls import url
from . import views

app_name = "auction"

urlpatterns = [
    url(r'^$', views.bidding_all, name='bidding_all'),
    url(r'^new/$', views.bidding_new, name='bidding_new'),
    url(r'^added/$', views.bidding_added, name='bidding_added'),
]

AgileEstate/estate/urls.py
from django.conf.urls import url
from . import views

app_name = "estate"

urlpatterns = [
    url(r'^$', views.estate_all, name='estate_all'),
    url(r'^new/$', views.estate_new, name='estate_new'),
    url(r'^created/$', views.estate_created, name='estate_created'),
    url(r'^selected/(\d+)/$', views.estate_selected, name='estate_selected'),
]

AgileEstate/users/urls.py
from django.conf.urls import url
from . import views

app_name = "users"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'profile/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile),
]

AgileEstate/AgileEstate/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect

def main_page(request):
    if request.method == 'GET':
        return render_to_response('main.html')

AgileEstate/AgileEstate/templates/main.html
<html>

<head>
    <title>AgileEstate</title>
    <meta charset="utf-8">
    <style type="text/css">
	@import url('https://fonts.googleapis.com/css?family=Lato');
        header {
            display: flex;
            flex-direction: row;
            font-family: 'Lato', sans-serif;
        }
        
        #title {
            padding: 0.1cm 0.5cm 0.1cm 0.5cm;
            margin: 0;
            flex-grow: 4;
            color: white;
            background-color: black;
	    
        }
        
        #login {
            text-align: center;
            padding: 0.1cm 0.5cm 0.1cm 0.5cm;
            margin: 0;
            flex-grow: 1;
            background-color: lightgrey;
        }
        
        body {
            margin: 0;
            background-color: #f2f2f2
	    
        }
        
        section {
            max-width: 900px;
            font-family: 'Lato', sans-serif;
        }
        
        #estate {
            margin: 0.5cm;
            padding: 0.1cm 0.5cm 0.1cm 0.5cm;
            background-color: white;
        }
        
        #link {
            display: block;
            line-height: 150%;
        }
    </style>
    <script>
        function mainHref() {
            var elem = document.getElementById("link");
            if (typeof elem !== 'undefined' && elem !== null) {
                var x = document.getElementById("link").href;
                document.getElementById("link").href = window.location.href + x;
            }
        }
        window.onload = mainHref();
    </script>
</head>

<body>
    <header>
        <h1 id="title">AgileEstate</h1>
        <h3 id="login"><a href={% url 'users:login_user' %} id="link">SIGN IN</a></h3>
    </header>

    <section>
        <div id="estate">
            <h3 id="greet">The world's largest agency for trade real estate.</h3>
            <div id="estatelinks">
                <a href={% url 'estate:estate_all' %} id="link">View property</a>
                <a href={% url 'estate:estate_new' %} id="link">Add property</a>
            </div>
	    <br>
            <div id="auctionlinks">
                <a href={% url 'auction:bidding_all' %} id="link">View auctions</a>
                <a href={% url 'auction:bidding_new' %} id="link">Add bidding</a>
            </div>
        </div>
    </section>

    <footer>

    </footer>
</body>

</html>